# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_main01(object):
    def setupUi(self, main01):
        main01.setObjectName("main01")
        main01.resize(226, 369)
        self.label = QtWidgets.QLabel(main01)
        self.label.setGeometry(QtCore.QRect(10, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(main01)
        self.spinBox.setGeometry(QtCore.QRect(150, 90, 51, 31))
        self.spinBox.setObjectName("spinBox")
        #self.spinBox.valueChanged.connect(self.initVm)
        self.label_2 = QtWidgets.QLabel(main01)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(main01)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox_3 = QtWidgets.QSpinBox(main01)
        self.spinBox_3.setGeometry(QtCore.QRect(130, 210, 71, 31))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_3.valueChanged.connect(self.initStorage)
        self.label_4 = QtWidgets.QLabel(main01)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        #self.label_5 = QtWidgets.QLabel(main01)
        #self.label_5.setGeometry(QtCore.QRect(20, 260, 131, 31))
        #font = QtGui.QFont()
        #font.setPointSize(10)
        #font.setBold(False)
        #font.setWeight(50)
        # self.label_5.setFont(font)
        # self.labe l_5.setObjectName("label_5")
        # self.textEdit = QtWidgets.QTextEdit(main01)
        # self.textEdit.setGeometry(QtCore.QRect(10, 290, 211, 21))
        # self.textEdit.valueChanged.connect(self.updatePath)
        # self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(main01)
        self.pushButton.setGeometry(QtCore.QRect(50, 320, 131, 34))
        self.pushButton.clicked.connect(self.installVM)
        self.pushButton.setObjectName("pushButton")
        self.doubleSpinBox = QtWidgets.QSpinBox(main01)
        self.doubleSpinBox.setGeometry(QtCore.QRect(120, 150, 81, 32))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox.valueChanged.connect(self.initRam)

        self.retranslateUi(main01)
        QtCore.QMetaObject.connectSlotsByName(main01)


    #def updateVM(self, main01):
    #    self.valueVm = self.spinBox.value()
    #    print (self.valueVm)
        
    #def updateStorage(self, main01):
    #    self.storage = self.spinBox_3.value()
    #    print (self.storage)
    
    #def updateRam(self, main01):
    #    self.valueRam = self.doubleSpinBox.value()*1024
    #    print (self.valueRam)

    def initRam(self, main01):
        
        print ("connected")

        self.valueRam = self.doubleSpinBox.value()*1024

        print (self.valueRam)

    def initStorage(self, main01):

        self.storage = self.spinBox_3.value()
        
        print (self.storage)
        
        # print (storage)
    def installVM(self, main01):

        virshCreate = "sudo -S <<< 123 virt-install --name test20 --ram {} --vcpu 2 --cdrom=/var/lib/libvirt/boot/archlinux-2020.08.01-x86_64.iso --disk path=/var/lib/libvirt/images/test20.qcow20,size={},format=qcow2,bus=virtio --graphics spice,listen=0.0.0.0,password=pass01 --noautoconsole --os-type=linux --os-variant=generic --check all=off".format(self.valueRam, self.storage)

        os.popen(virshCreate)

    def retranslateUi(self, main01):
        _translate = QtCore.QCoreApplication.translate
        main01.setWindowTitle(_translate("main01", "main01"))
        self.label.setText(_translate("main01", "VM amount:"))
        self.label_2.setText(_translate("main01", "Assigned RAM"))
        self.label_3.setText(_translate("main01", "Assigned Storage:"))
        self.label_4.setText(_translate("main01", "VM Creator"))
        #self.label_5.setText(_translate("main01", "Image/ISO location:"))
        self.pushButton.setText(_translate("main01", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main01 = QtWidgets.QWidget()
    ui = Ui_main01()
    ui.setupUi(main01)
    main01.show()
    sys.exit(app.exec_())
