# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from main_backend import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1030, 649)
        
        # The Following Code builds UI
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabThree = QtWidgets.QTabWidget(Dialog)
        
        # This represents each of the different screens used for managing oneLab (tabs)
        self.tabThree.setObjectName("tabThree")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        # Container for buttons at the top of Tab 1 (VM managerment screen)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        # The selection box used to select which PC to interect with
        self.pcSelector = QtWidgets.QComboBox(self.tab)
        self.pcSelector.setObjectName("pcSelector")
        # self.pcSelector.currentIndexChanged.connect(self.machineTracker)
        self.pcSelector.addItem("")
        self.pcSelector.addItem("")
        self.pcSelector.addItem("")
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.pcSelector.addItem('')
        self.horizontalLayout_2.addWidget(self.pcSelector)
        
        # This is the container for the 3 buttons on the right side of the selection box
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.onOffBtn = QtWidgets.QPushButton(self.tab)
        
        # This buttons turns machines on and off (toggleable)
        self.onOffBtn.setObjectName("onOffBtn")
        self.horizontalLayout.addWidget(self.onOffBtn)
        self.onOffBtn.setCheckable(True)
        self.onOffBtn.clicked.connect(self.statusBtnOnOff)
        
        # This buttons pauses and resumes machines (toggleable)
        self.pausePlayBtn = QtWidgets.QPushButton(self.tab)
        self.pausePlayBtn.setObjectName("pausePlayBtn")
        self.horizontalLayout.addWidget(self.pausePlayBtn)
        self.pausePlayBtn.setCheckable(True)
        self.pausePlayBtn.clicked.connect(self.statPauseBtn)
        
        # This button will launch a spice client to the selected machine
        self.interactBtn = QtWidgets.QPushButton(self.tab)
        self.interactBtn.setObjectName("interactBtn")
        self.interactBtn.setCheckable(True)
        self.horizontalLayout.addWidget(self.interactBtn)
        
        # This is the main area of the window container the active screens 
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.mainBody = QtWidgets.QScrollArea(self.tab)
        self.mainBody.setMinimumSize(QtCore.QSize(0, 0))
        self.mainBody.setWidgetResizable(True)
        self.mainBody.setObjectName("mainBody")
        self.main = QtWidgets.QWidget()
        self.main.setGeometry(QtCore.QRect(0, 0, 973, 4000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMinimumSize(QtCore.QSize(0, 4000))
        self.main.setObjectName("main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        # The following represents each individual window
        self.box_07 = QtWidgets.QFrame(self.main)
        self.box_07.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_07.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_07.setObjectName("box_07")
        self.label_6 = QtWidgets.QLabel(self.box_07)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.box_07, 3, 0, 1, 1)
        
        self.box_25 = QtWidgets.QFrame(self.main)
        self.box_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_25.setObjectName("box_25")
        self.monitor_label_25 = QtWidgets.QLabel(self.box_25)
        self.monitor_label_25.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_25.setObjectName("monitor_label_25")
        self.gridLayout_2.addWidget(self.box_25, 9, 0, 1, 1)
        
        self.box_02 = QtWidgets.QFrame(self.main)
        self.box_02.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_02.setObjectName("box_02")
        self.label = QtWidgets.QLabel(self.box_02)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.box_02, 1, 1, 1, 1)
        
        self.box_05 = QtWidgets.QFrame(self.main)
        self.box_05.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_05.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_05.setObjectName("box_05")
        self.label_4 = QtWidgets.QLabel(self.box_05)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.box_05, 2, 1, 1, 1)
        
        self.box_10 = QtWidgets.QFrame(self.main)
        self.box_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_10.setObjectName("box_10")
        self.monitor_label_10 = QtWidgets.QLabel(self.box_10)
        self.monitor_label_10.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_10.setObjectName("monitor_label_10")
        self.gridLayout_2.addWidget(self.box_10, 4, 0, 1, 1)
        
        self.box_15 = QtWidgets.QFrame(self.main)
        self.box_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_15.setObjectName("box_15")
        self.monitor_label_15 = QtWidgets.QLabel(self.box_15)
        self.monitor_label_15.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_15.setObjectName("monitor_label_15")
        self.gridLayout_2.addWidget(self.box_15, 5, 2, 1, 1)
        
        self.box_04 = QtWidgets.QFrame(self.main)
        self.box_04.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_04.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_04.setObjectName("box_04")
        self.label_3 = QtWidgets.QLabel(self.box_04)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.box_04, 2, 0, 1, 1)
        
        self.box_14 = QtWidgets.QFrame(self.main)
        self.box_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_14.setObjectName("box_14")
        self.monitor_label_14 = QtWidgets.QLabel(self.box_14)
        self.monitor_label_14.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_14.setObjectName("monitor_label_14")
        self.gridLayout_2.addWidget(self.box_14, 5, 1, 1, 1)
        
        self.box_26 = QtWidgets.QFrame(self.main)
        self.box_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_26.setObjectName("box_26")
        self.monitor_label_26 = QtWidgets.QLabel(self.box_26)
        self.monitor_label_26.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_26.setObjectName("monitor_label_26")
        self.gridLayout_2.addWidget(self.box_26, 9, 1, 1, 1)
        
        self.box_33 = QtWidgets.QFrame(self.main)
        self.box_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_33.setObjectName("box_33")
        self.monitor_label_33 = QtWidgets.QLabel(self.box_33)
        self.monitor_label_33.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_33.setObjectName("monitor_label_33")
        self.gridLayout_2.addWidget(self.box_33, 11, 2, 1, 1)
        
        self.box_17 = QtWidgets.QFrame(self.main)
        self.box_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_17.setObjectName("box_17")
        self.monitor_label_17 = QtWidgets.QLabel(self.box_17)
        self.monitor_label_17.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_17.setObjectName("monitor_label_17")
        self.gridLayout_2.addWidget(self.box_17, 6, 1, 1, 1)
        
        self.box_16 = QtWidgets.QFrame(self.main)
        self.box_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_16.setObjectName("box_16")
        self.monitor_label_16 = QtWidgets.QLabel(self.box_16)
        self.monitor_label_16.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_16.setObjectName("monitor_label_16")
        self.gridLayout_2.addWidget(self.box_16, 6, 0, 1, 1)
        
        self.box_13 = QtWidgets.QFrame(self.main)
        self.box_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_13.setObjectName("box_13")
        self.monitor_label_13 = QtWidgets.QLabel(self.box_13)
        self.monitor_label_13.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_13.setObjectName("monitor_label_13")
        self.gridLayout_2.addWidget(self.box_13, 5, 0, 1, 1)
        
        self.box_11 = QtWidgets.QFrame(self.main)
        self.box_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_11.setObjectName("box_11")
        self.monitor_label_11 = QtWidgets.QLabel(self.box_11)
        self.monitor_label_11.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_11.setObjectName("monitor_label_11")
        self.gridLayout_2.addWidget(self.box_11, 4, 1, 1, 1)
        
        self.box_22 = QtWidgets.QFrame(self.main)
        self.box_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_22.setObjectName("box_22")
        self.monitor_label_22 = QtWidgets.QLabel(self.box_22)
        self.monitor_label_22.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_22.setObjectName("monitor_label_22")
        self.gridLayout_2.addWidget(self.box_22, 8, 0, 1, 1)
        
        self.box_21 = QtWidgets.QFrame(self.main)
        self.box_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_21.setObjectName("box_21")
        self.monitor_label_21 = QtWidgets.QLabel(self.box_21)
        self.monitor_label_21.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_21.setObjectName("monitor_label_21")
        self.gridLayout_2.addWidget(self.box_21, 7, 2, 1, 1)
        
        self.box_20 = QtWidgets.QFrame(self.main)
        self.box_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_20.setObjectName("box_20")
        self.monitor_label_20 = QtWidgets.QLabel(self.box_20)
        self.monitor_label_20.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_20.setObjectName("monitor_label_20")
        self.gridLayout_2.addWidget(self.box_20, 7, 1, 1, 1)
        
        self.box_09 = QtWidgets.QFrame(self.main)
        self.box_09.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_09.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_09.setObjectName("box_09")
        self.monitor_label_09 = QtWidgets.QLabel(self.box_09)
        self.monitor_label_09.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_09.setObjectName("monitor_label_09")
        self.gridLayout_2.addWidget(self.box_09, 3, 2, 1, 1)
        
        self.box_29 = QtWidgets.QFrame(self.main)
        self.box_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_29.setObjectName("box_29")
        self.monitor_label_29 = QtWidgets.QLabel(self.box_29)
        self.monitor_label_29.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_29.setObjectName("monitor_label_29")
        self.gridLayout_2.addWidget(self.box_29, 10, 1, 1, 1)
        
        self.box_12 = QtWidgets.QFrame(self.main)
        self.box_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_12.setObjectName("box_12")
        self.monitor_label_12 = QtWidgets.QLabel(self.box_12)
        self.monitor_label_12.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_12.setObjectName("monitor_label_12")
        self.gridLayout_2.addWidget(self.box_12, 4, 2, 1, 1)
        
        self.box_08 = QtWidgets.QFrame(self.main)
        self.box_08.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_08.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_08.setObjectName("box_08")
        self.monitor_label_08 = QtWidgets.QLabel(self.box_08)
        self.monitor_label_08.setGeometry(QtCore.QRect(20, 10, 101, 21))
        self.monitor_label_08.setObjectName("monitor_label_08")
        self.gridLayout_2.addWidget(self.box_08, 3, 1, 1, 1)
        
        self.box_32 = QtWidgets.QFrame(self.main)
        self.box_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_32.setObjectName("box_32")
        self.monitor_label_32 = QtWidgets.QLabel(self.box_32)
        self.monitor_label_32.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_32.setObjectName("monitor_label_32")
        self.gridLayout_2.addWidget(self.box_32, 11, 1, 1, 1)
        
        self.box_35 = QtWidgets.QFrame(self.main)
        self.box_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_35.setObjectName("box_35")
        self.monitor_label_35 = QtWidgets.QLabel(self.box_35)
        self.monitor_label_35.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_35.setObjectName("monitor_label_35")
        self.gridLayout_2.addWidget(self.box_35, 12, 1, 1, 1)
        
        self.box_06 = QtWidgets.QFrame(self.main)
        self.box_06.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_06.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_06.setObjectName("box_06")
        self.label_5 = QtWidgets.QLabel(self.box_06)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 101, 21))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.box_06, 2, 2, 1, 1)
        
        self.box_24 = QtWidgets.QFrame(self.main)
        self.box_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_24.setObjectName("box_24")
        self.monitor_label_24 = QtWidgets.QLabel(self.box_24)
        self.monitor_label_24.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_24.setObjectName("monitor_label_24")
        self.gridLayout_2.addWidget(self.box_24, 8, 2, 1, 1)
        
        self.box_37 = QtWidgets.QFrame(self.main)
        self.box_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_37.setObjectName("box_37")
        self.monitor_label_34 = QtWidgets.QLabel(self.box_37)
        self.monitor_label_34.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_34.setObjectName("monitor_label_34")
        self.gridLayout_2.addWidget(self.box_37, 12, 0, 1, 1)
        
        self.box_18 = QtWidgets.QFrame(self.main)
        self.box_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_18.setObjectName("box_18")
        self.monitor_label_18 = QtWidgets.QLabel(self.box_18)
        self.monitor_label_18.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_18.setObjectName("monitor_label_18")
        self.gridLayout_2.addWidget(self.box_18, 6, 2, 1, 1)
        
        self.box_03 = QtWidgets.QFrame(self.main)
        self.box_03.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_03.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_03.setObjectName("box_03")
        self.label_2 = QtWidgets.QLabel(self.box_03)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.box_03, 1, 2, 1, 1)
        
        self.box_19 = QtWidgets.QFrame(self.main)
        self.box_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_19.setObjectName("box_19")
        self.monitor_label_19 = QtWidgets.QLabel(self.box_19)
        self.monitor_label_19.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_19.setObjectName("monitor_label_19")
        self.gridLayout_2.addWidget(self.box_19, 7, 0, 1, 1)
        
        self.box_23 = QtWidgets.QFrame(self.main)
        self.box_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_23.setObjectName("box_23")
        self.monitor_label_23 = QtWidgets.QLabel(self.box_23)
        self.monitor_label_23.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_23.setObjectName("monitor_label_23")
        self.gridLayout_2.addWidget(self.box_23, 8, 1, 1, 1)
        
        self.box_28 = QtWidgets.QFrame(self.main)
        self.box_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_28.setObjectName("box_28")
        self.monitor_label_28 = QtWidgets.QLabel(self.box_28)
        self.monitor_label_28.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_28.setObjectName("monitor_label_28")
        self.gridLayout_2.addWidget(self.box_28, 10, 0, 1, 1)
        
        self.box_01 = QtWidgets.QFrame(self.main)
        self.box_01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_01.setObjectName("box_01")
        self.label_7 = QtWidgets.QLabel(self.box_01)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.box_01, 1, 0, 1, 1)
        
        self.box_27 = QtWidgets.QFrame(self.main)
        self.box_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_27.setObjectName("box_27")
        self.monitor_label_27 = QtWidgets.QLabel(self.box_27)
        self.monitor_label_27.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_27.setObjectName("monitor_label_27")
        self.gridLayout_2.addWidget(self.box_27, 9, 2, 1, 1)
        
        self.box_31 = QtWidgets.QFrame(self.main)
        self.box_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_31.setObjectName("box_31")
        self.monitor_label_31 = QtWidgets.QLabel(self.box_31)
        self.monitor_label_31.setGeometry(QtCore.QRect(20, 10, 101, 21))
        self.monitor_label_31.setObjectName("monitor_label_31")
        self.gridLayout_2.addWidget(self.box_31, 11, 0, 1, 1)
        
        self.box_30 = QtWidgets.QFrame(self.main)
        self.box_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_30.setObjectName("box_30")
        self.monitor_label_30 = QtWidgets.QLabel(self.box_30)
        self.monitor_label_30.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_30.setObjectName("monitor_label_30")
        self.gridLayout_2.addWidget(self.box_30, 10, 2, 1, 1)
        
        self.box_36 = QtWidgets.QFrame(self.main)
        self.box_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_36.setObjectName("box_36")
        self.monitor_label_36 = QtWidgets.QLabel(self.box_36)
        self.monitor_label_36.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.monitor_label_36.setObjectName("monitor_label_36")
        self.gridLayout_2.addWidget(self.box_36, 12, 2, 1, 1)
        
        #
        # This is the start of the second tab 
        # The following blocks are set as the main container of tab2 
        self.mainBody.setWidget(self.main)
        self.gridLayout_3.addWidget(self.mainBody, 1, 0, 1, 1)
        self.tabThree.addTab(self.tab, "")
        
        # This si the reference to the grid layout of tab2
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cmCreateContainer = QtWidgets.QFrame(self.tab_2)
        self.cmCreateContainer.setMinimumSize(QtCore.QSize(330, 0))
        self.cmCreateContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cmCreateContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cmCreateContainer.setObjectName("cmCreateContainer")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.cmCreateContainer)
        self.gridLayout_6.setObjectName("gridLayout_6")
        
        # The following are the selectors used to determine how much ram and storage space to assign and how many VM's to creat.
        # Assigned RAM Label
        self.ramAmountName = QtWidgets.QLabel(self.cmCreateContainer)
        self.ramAmountName.setObjectName("ramAmountName")
        self.gridLayout_6.addWidget(self.ramAmountName, 3, 0, 1, 1)
        
        # Storage aissgined Label 
        self.storageAmountSelect = QtWidgets.QSpinBox(self.cmCreateContainer)
        self.storageAmountSelect.setObjectName("storageAmountSelect")
        # self.storageAmountSelect.valueChanged.connect(self.vmManagement)
        
        self.gridLayout_6.addWidget(self.storageAmountSelect, 6, 0, 1, 1)
        self.vmStorageName = QtWidgets.QLabel(self.cmCreateContainer)
        self.vmStorageName.setObjectName("vmStorageName")
        self.gridLayout_6.addWidget(self.vmStorageName, 5, 0, 1, 1)
        self.vmAmountName = QtWidgets.QLabel(self.cmCreateContainer)
        self.vmAmountName.setObjectName("vmAmountName")
        self.gridLayout_6.addWidget(self.vmAmountName, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.cmCreateContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 4, 1, 1, 1)
        self.machineName = QtWidgets.QLabel(self.cmCreateContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.machineName.setFont(font)
        self.machineName.setObjectName("machineName")
        self.gridLayout_6.addWidget(self.machineName, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.cmCreateContainer)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 2)
        
        # How many VM's to create selector
        self.vmAmountSelect = QtWidgets.QSpinBox(self.cmCreateContainer)
        self.vmAmountSelect.setObjectName("vmAmountSelect")
        self.gridLayout_6.addWidget(self.vmAmountSelect, 2, 0, 1, 1)
        # self.vmAmountSelect.valueChanged.connect(self.vmManagement)
        
        # Ram selector
        self.ramAmountSelect = QtWidgets.QSpinBox(self.cmCreateContainer)
        self.ramAmountSelect.setObjectName("ramAmountSelect")
        # self.ramAmountSelect.valueChanged.connect(self.vmManagement)
        
        self.gridLayout_6.addWidget(self.ramAmountSelect, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.cmCreateContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 6, 1, 1, 1)
        
        # The button to trigger the function to build the vm's  
        self.creatVmBtn = QtWidgets.QPushButton(self.cmCreateContainer)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.creatVmBtn.setFont(font)
        self.creatVmBtn.setObjectName("creatVmBtn")
        self.gridLayout_6.addWidget(self.creatVmBtn, 7, 0, 1, 2)
        self.creatVmBtn.clicked.connect(self.vmManagement)
        
        self.gridLayout_4.addWidget(self.cmCreateContainer, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(300, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.tab_2)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 700))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 0, 1, 1)
        self.name_input = QtWidgets.QTextEdit(self.frame_10)
        self.name_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.name_input.setObjectName("name_input")
        self.gridLayout_7.addWidget(self.name_input, 2, 0, 1, 1)
        self.userNameInput = QtWidgets.QTextEdit(self.frame_10)
        self.userNameInput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userNameInput.setObjectName("userNameInput")
        self.gridLayout_7.addWidget(self.userNameInput, 4, 0, 1, 1)
        self.inputLabel = QtWidgets.QLabel(self.frame_10)
        self.inputLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.inputLabel.setObjectName("inputLabel")
        self.gridLayout_7.addWidget(self.inputLabel, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 5, 0, 1, 1)
        self.password_input = QtWidgets.QTextEdit(self.frame_10)
        self.password_input.setMinimumSize(QtCore.QSize(0, 30))
        self.password_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.password_input.setObjectName("password_input")
        self.gridLayout_7.addWidget(self.password_input, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setMinimumSize(QtCore.QSize(0, 50))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 7, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_10, 0, 2, 1, 1)
        self.tabThree.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabThree, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabThree.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        
        # The following represent the contecnts of each cob-box selection
        self.pcSelector.setItemText(0, _translate("Dialog", "all"))
        self.pcSelector.setItemText(1, _translate("Dialog", "monitor-02"))
        self.pcSelector.setItemText(2, _translate('Dialog', 'PC-2'))
        self.pcSelector.setItemText(3, _translate('Dialog', 'PC-3'))
        self.pcSelector.setItemText(4, _translate('Dialog', 'PC-4'))
        self.pcSelector.setItemText(5, _translate('Dialog', 'PC-5'))
        self.pcSelector.setItemText(6, _translate('Dialog', 'PC-6'))
        self.pcSelector.setItemText(7, _translate('Dialog', 'PC-7'))
        self.pcSelector.setItemText(8, _translate('Dialog', 'PC-8'))
        self.pcSelector.setItemText(9, _translate('Dialog', 'PC-9'))
        self.pcSelector.setItemText(10, _translate('Dialog', 'PC-10'))
        self.pcSelector.setItemText(11, _translate('Dialog', 'PC-11'))
        self.pcSelector.setItemText(12, _translate('Dialog', 'PC-12'))
        self.pcSelector.setItemText(13, _translate('Dialog', 'PC-13'))
        self.pcSelector.setItemText(14, _translate('Dialog', 'PC-14'))
        self.pcSelector.setItemText(15, _translate('Dialog', 'PC-15'))
        self.pcSelector.setItemText(16, _translate('Dialog', 'PC-16'))
        self.pcSelector.setItemText(17, _translate('Dialog', 'PC-17'))
        self.pcSelector.setItemText(18, _translate('Dialog', 'PC-18'))
        self.pcSelector.setItemText(19, _translate('Dialog', 'PC-19'))
        self.pcSelector.setItemText(20, _translate('Dialog', 'PC-20'))
        self.pcSelector.setItemText(21, _translate('Dialog', 'PC-21'))
        self.pcSelector.setItemText(22, _translate('Dialog', 'PC-22'))
        self.pcSelector.setItemText(23, _translate('Dialog', 'PC-23'))
        self.pcSelector.setItemText(24, _translate('Dialog', 'PC-24'))
        self.pcSelector.setItemText(25, _translate('Dialog', 'PC-25'))
        self.pcSelector.setItemText(26, _translate('Dialog', 'PC-26'))
        self.pcSelector.setItemText(27, _translate('Dialog', 'PC-27'))
        self.pcSelector.setItemText(28, _translate('Dialog', 'PC-28'))
        self.pcSelector.setItemText(29, _translate('Dialog', 'PC-29'))
        self.pcSelector.setItemText(30, _translate('Dialog', 'PC-30'))
        self.pcSelector.setItemText(31, _translate('Dialog', 'PC-31'))
        self.pcSelector.setItemText(32, _translate('Dialog', 'PC-32'))
        self.pcSelector.setItemText(33, _translate('Dialog', 'PC-33'))
        self.pcSelector.setItemText(34, _translate('Dialog', 'PC-34'))
        self.pcSelector.setItemText(35, _translate('Dialog', 'PC-35'))
        
        self.onOffBtn.setText(_translate("Dialog", "Start / Stop"))
        self.pausePlayBtn.setText(_translate("Dialog", "Pause / Play"))
        self.interactBtn.setText(_translate("Dialog", "Interact"))
        self.label_6.setText(_translate("Dialog", "PC-07"))
        self.monitor_label_25.setText(_translate("Dialog", "PC-25"))
        self.label.setText(_translate("Dialog", "PC-02"))
        self.label_4.setText(_translate("Dialog", "PC-05"))
        self.monitor_label_10.setText(_translate("Dialog", "PC-10"))
        self.monitor_label_15.setText(_translate("Dialog", "PC-15"))
        self.label_3.setText(_translate("Dialog", "PC-04"))
        self.monitor_label_14.setText(_translate("Dialog", "PC-14"))
        self.monitor_label_26.setText(_translate("Dialog", "PC-26"))
        self.monitor_label_33.setText(_translate("Dialog", "PC-33"))
        self.monitor_label_17.setText(_translate("Dialog", "PC-17"))
        self.monitor_label_16.setText(_translate("Dialog", "PC-16"))
        self.monitor_label_13.setText(_translate("Dialog", "PC-13"))
        self.monitor_label_11.setText(_translate("Dialog", "PC-11"))
        self.monitor_label_22.setText(_translate("Dialog", "PC-22"))
        self.monitor_label_21.setText(_translate("Dialog", "PC-21"))
        self.monitor_label_20.setText(_translate("Dialog", "PC-20"))
        self.monitor_label_09.setText(_translate("Dialog", "PC-09"))
        self.monitor_label_29.setText(_translate("Dialog", "PC-29"))
        self.monitor_label_12.setText(_translate("Dialog", "PC-12"))
        self.monitor_label_08.setText(_translate("Dialog", "PC-08"))
        self.monitor_label_32.setText(_translate("Dialog", "PC-32"))
        self.monitor_label_35.setText(_translate("Dialog", "PC-35"))
        self.label_5.setText(_translate("Dialog", "PC-06"))
        self.monitor_label_24.setText(_translate("Dialog", "PC-24"))
        self.monitor_label_34.setText(_translate("Dialog", "PC-34"))
        self.monitor_label_18.setText(_translate("Dialog", "PC-18"))
        self.label_2.setText(_translate("Dialog", "PC-03"))
        self.monitor_label_19.setText(_translate("Dialog", "PC-19"))
        self.monitor_label_23.setText(_translate("Dialog", "PC-23"))
        self.monitor_label_28.setText(_translate("Dialog", "PC-28"))
        self.label_7.setText(_translate("Dialog", "PC-01"))
        self.monitor_label_27.setText(_translate("Dialog", "PC-27"))
        self.monitor_label_31.setText(_translate("Dialog", "PC-31"))
        self.monitor_label_30.setText(_translate("Dialog", "PC-30"))
        self.monitor_label_36.setText(_translate("Dialog", "PC-36"))
        self.tabThree.setTabText(self.tabThree.indexOf(self.tab), _translate("Dialog", "Lab View"))
        self.ramAmountName.setText(_translate("Dialog", "Ram:"))
        self.vmStorageName.setText(_translate("Dialog", "Storage: "))
        self.vmAmountName.setText(_translate("Dialog", "Amount:"))
        self.label_16.setText(_translate("Dialog", "GB"))
        self.machineName.setText(_translate("Dialog", "VM\'s"))
        self.label_10.setText(_translate("Dialog", "Create VM"))
        self.label_15.setText(_translate("Dialog", "GB"))
        self.creatVmBtn.setText(_translate("Dialog", "Create"))
        self.label_11.setText(_translate("Dialog", "Name"))
        self.inputLabel.setText(_translate("Dialog", "User Name"))
        self.label_13.setText(_translate("Dialog", "Password"))
        self.label_12.setText(_translate("Dialog", "Create User"))
        self.pushButton.setText(_translate("Dialog", "Create"))
        self.tabThree.setTabText(self.tabThree.indexOf(self.tab_2), _translate("Dialog", "Creator"))
        
        
    ################################
    # This is the Temorary Backend #
    ################################
    
    #=================#
    # Visal functions #
    #=================#
    
    # Stop/start button 
    def statusBtnOnOff(self):
  
       self.ofBtn = self.onOffBtn
       self.ppBtn = self.pausePlayBtn
       
       if self.ofBtn.isChecked():
           
           # Sets the on/off button to green when clicked
           self.ofBtn.setStyleSheet("background-color: lightgreen")
           
           # Sets the pause/play button to green when on/offbtn is clicked
           self.ppBtn.setStyleSheet("background-color: lightgreen")
               
       else:
            
            # Sets on/off button to red when button is unchecked
            self.ofBtn.setStyleSheet("background-color: red")
        
            # Sets pause/play button to red when on/off button is unchecked
            self.ppBtn.setStyleSheet("background-color: red")
            
    # Handler for pause/play button color status
    def statPauseBtn(self):
        
        # Handler for pause/play button     
       if self.ppBtn.isChecked():
           
           #Turns background color of pause/play button to red if it's checked
           self.ppBtn.setStyleSheet("background-color: red")
           
       else:
           
           # Turns pause/play button back to green when checked again
           self.ppBtn.setStyleSheet("background-color: lightgreen")
           
           
    #==============================#
    # Backend machanical functions #
    #==============================# 
     
     
    # Vm creation sectioin
    def vmManagement(self):
        
        # Variable container number for amount of VM's to create
        vmCreateAmoutn = 0
        
        # Stores Value for ram allocated to each VM 
        vmAmount = self.vmAmountSelect.value()
        ramAmount =  self.ramAmountSelect.value()*1024
        storageAmount = self.storageAmountSelect.value()
        
        virsh_command = ("virt-install --name test1 --ram '{}' --vcpu 2 --cdrom=/home/brilliant/Downloads/archlinux-2020.08.01-x86_64.iso --disk path=/var/lib/libvirt/images/test1.qcow2,size='{}',format=qcow2,bus=virtio --graphics spice,listen=0.0.0.0,password=123 --noautoconsole --os-type=linux --os-variant=generic".format(ramAmount, storageAmount))
        
        print (virsh_command)

# Curently workign on backend 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
